config/routes.rb
Rails.application.routes.draw do
  
  ## Frontend Website Routes
  root to: 'frontend#index'
  get 'blog', to: 'frontend#blog', as: :blog
  get 'order', to: 'frontend#order', as: :order
  get 'products', to: 'frontend#products', as: :frontend_products
  get 'about', to: 'frontend#about', as: :about
  get 'contact', to: 'frontend#contact', as: :contact
  get 'cart', to: 'frontend#cart', as: :cart
  get 'checkout/account', to: 'frontend#checkout_account', as: :checkout_account
  get 'checkout/shipping', to: 'frontend#checkout_shipping', as: :checkout_shipping
  get 'checkout/payment', to: 'frontend#checkout_payment', as: :checkout_payment
  get 'checkout/confirmation', to: 'frontend#checkout_confirmation', as: :checkout_confirmation

  resources :order_items, only: [:create, :update, :destroy]
  resources :orders, only: [:update]

  post 'addresses', to: 'addresses#create'
  post 'checkout/payment', to: 'frontend#checkout_payment_fulfillment', as: :checkout_payment_fulfillment

  ## User Account Routes
  get 'account', to: 'account#index', as: :account
  scope 'account' do
    get 'subscriptions', to: 'account#subscriptions', as: :account_subscriptions
    post 'subscriptions/:id/cancel', to: 'subscriptions#cancel', as: :cancel_subscription
    # get 'billing', to: 'account#billing', as: :account_billing
    get 'settings', to: 'account#settings', as: :account_settings
    resources :addresses, except: :destroy
  end


  ## Verify Let's Encrypt
  get '.well-known/acme-challenge/krDZFT9l6mV5mh29OuTAinc3-uCDZudYljSon6gH41I', to: 'frontend#letsencrypt_develop'
  get '.well-known/acme-challenge/bZQzDR1ujn0FQ0UuIJYwrpHINu-Jkpnv4I1XtAvcNhs', to: 'frontend#letsencrypt_staging'
  get '.well-known/acme-challenge/4ahKSK8Se_NIIpBnfipB0xIFNU6mhg69pocJU4GzV8o', to: 'frontend#letsencrypt_production'


  ## 301's from old Website
  get 'blogs/news', to: redirect('http://blog.herbata.co', status: 301)
  get 'blogs/news/:name', to: redirect('http://blog.herbata.co/%{name}', status: 301)
  get 'collections/all', to: redirect('https://herbata.co/products', status: 301)
  get 'products/one-month-subscription', to: redirect('https://herbata.co/products', status: 301)
  get 'products/3-month-subscription', to: redirect('https://herbata.co/products', status: 301)

  

  ## Devise Routes
  devise_for :users, :controllers => {
    registrations: 'registrations',
    sessions: 'sessions',
    passwords: 'passwords'
  }
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    delete 'logout', to: 'devise/sessions#destroy'
  end


  ## Backend Access Routes
  get 'farm', to: 'dashboard#index', as: :dashboard
  scope 'farm' do
    resources :orders, only: [:index, :show, :update] do
      resources :order_statuses, only: [:index, :create]
    end
    get 'orders/:id', to: 'orders#show', as: :order_detail

    resources :product_groups
    resources :products
    resources :coupons
    resources :subscriptions
    resources :customers
  end
end

app/views/shared/_header.html.erb
<nav class="navbar fixed-top navbar-toggleable-md navbar-inverse bg-primary">
  <div class="container">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#">
      <%= image_tag "white.logo@2x", width: 39, height: 36 %>
      <%#&nbsp;&nbsp;|&nbsp;&nbsp;
      The Farm%>
      &nbsp;&nbsp;&nbsp;&nbsp;
    </a>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Sales
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to "Orders", orders_path, class: "dropdown-item" %>
            <%= link_to "Customers", customers_path, class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%#<%= link_to "Invoices", "/", class: "dropdown-item" %>
            <%#<%= link_to "Charges", charges_path, class: "dropdown-item" %>
            <%= link_to "Subscriptions", subscriptions_path, class: "dropdown-item" %>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Store
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to "Products", products_path, class: "dropdown-item" %>
            <%= link_to "Coupons", coupons_path, class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "Products Groups", product_groups_path, class: "dropdown-item" %>
            <a class="dropdown-item" href="#">Discounts</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Admin
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#">Users</a>
            <a class="dropdown-item" href="#">Order Statuses</a>
            <a class="dropdown-item" href="#">Product Types</a>
          </div>
        </li>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.name %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <h6 class="dropdown-header">Settings</h6>
            <a class="dropdown-item" href="#">Account</a>
            <a class="dropdown-item" href="#">Notifications</a>
            <div class="dropdown-divider"></div>
            <%= link_to "Logout", destroy_user_session_path, { method: :delete, class: "dropdown-item" } %>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_nav.html.erb
<nav class="fc-nav">
  <div class="fc-nav__logo">
    <%= image_tag "white.logo", width: "75", height: "70" %>
  </div>

  <!-- <form class="aor" _lpchecked="1">
    <input class="form-control" type="text" placeholder="Search...">
    <button type="submit" class="fm">
      <span class="bv adn"></span>
    </button>
  </form> -->

  <ul class="nav nav-pills nav-stacked">
    <li class="nav-label">Overview</li>
    <li class="nav-item">
      <a class="nav-link active" href="#">Dashboard</a>
    </li>

    <li class="nav-label">Ecommerce</li>
    <li class="nav-item"><%= link_to "Orders", orders_path, class: 'nav-link' %></li>
    <li class="nav-item"><%= link_to "Subscriptions", subscriptions_path, class: 'nav-link' %></li>
    <li class="nav-item"><%= link_to "Coupons", coupons_path, class: 'nav-link' %></li>

    <li class="nav-label">Products</li>
    <li class="nav-item"><%= link_to "Products", products_path, class: 'nav-link' %></li>
    <li class="nav-item"><%= link_to "Product Groups", product_groups_path, class: 'nav-link' %></li>

    <li class="nav-label">Account</li>
    <li class="nav-item">
      <a class="nav-link" href="#">Settings</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Logout</a>
    </li>
  </ul>
</nav>