config/routes.rb
Rails.application.routes.draw do
  
  ## Frontend Website Routes
  root to: 'frontend#index'
  get 'blog', to: 'frontend#blog', as: :blog
  get 'order', to: 'frontend#order', as: :order
  get 'products', to: 'frontend#products', as: :frontend_products
  get 'about', to: 'frontend#about', as: :about
  get 'contact', to: 'frontend#contact', as: :contact
  get 'cart', to: 'frontend#cart', as: :cart
  get 'checkout/account', to: 'frontend#checkout_account', as: :checkout_account
  get 'checkout/shipping', to: 'frontend#checkout_shipping', as: :checkout_shipping
  get 'checkout/payment', to: 'frontend#checkout_payment', as: :checkout_payment
  get 'checkout/confirmation', to: 'frontend#checkout_confirmation', as: :checkout_confirmation

  resources :order_items, only: [:create, :update, :destroy]
  resources :orders, only: [:update]

  post 'addresses', to: 'addresses#create'
  post 'checkout/payment', to: 'frontend#checkout_payment_fulfillment', as: :checkout_payment_fulfillment

  ## User Account Routes
  get 'account', to: 'account#index', as: :account
  scope 'account' do
    get 'subscriptions', to: 'account#subscriptions', as: :account_subscriptions
    post 'subscriptions/:id/cancel', to: 'subscriptions#cancel', as: :cancel_subscription
    # get 'billing', to: 'account#billing', as: :account_billing
    get 'settings', to: 'account#settings', as: :account_settings
    resources :addresses, except: :destroy
  end


  ## Verify Let's Encrypt
  get '.well-known/acme-challenge/krDZFT9l6mV5mh29OuTAinc3-uCDZudYljSon6gH41I', to: 'frontend#letsencrypt_develop'
  get '.well-known/acme-challenge/bZQzDR1ujn0FQ0UuIJYwrpHINu-Jkpnv4I1XtAvcNhs', to: 'frontend#letsencrypt_staging'
  get '.well-known/acme-challenge/4ahKSK8Se_NIIpBnfipB0xIFNU6mhg69pocJU4GzV8o', to: 'frontend#letsencrypt_production'


  ## 301's from old Website
  get 'blogs/news', to: redirect('http://blog.herbata.co', status: 301)
  get 'blogs/news/:name', to: redirect('http://blog.herbata.co/%{name}', status: 301)
  get 'collections/all', to: redirect('https://herbata.co/products', status: 301)
  get 'products/one-month-subscription', to: redirect('https://herbata.co/products', status: 301)
  get 'products/3-month-subscription', to: redirect('https://herbata.co/products', status: 301)

  

  ## Devise Routes
  devise_for :users, :controllers => {
    registrations: 'registrations',
    sessions: 'sessions',
    passwords: 'passwords'
  }
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    delete 'logout', to: 'devise/sessions#destroy'
  end


  ## Backend Access Routes
  get 'farm', to: 'dashboard#index', as: :dashboard
  scope 'farm' do
    resources :orders, only: [:index, :show, :update] do
      resources :order_statuses, only: [:index, :create]
    end
    get 'orders/:id', to: 'orders#show', as: :order_detail

    resources :product_groups
    resources :products
    resources :coupons
    resources :subscriptions
    resources :customers
  end
end

app/models/product_group.rb
class ProductGroup < ApplicationRecord
  has_many :products
end

app/controllers/product_groups_controller.rb
class ProductGroupsController < ApplicationController
  layout "application"
  before_action :authenticate_user!
  
  before_action :set_product_group, only: [:show, :edit, :update, :destroy]

  # GET /product_groups
  # GET /product_groups.json
  def index
    @product_groups = ProductGroup.all
  end

  # GET /product_groups/1
  # GET /product_groups/1.json
  def show
  end

  # GET /product_groups/new
  def new
    @product_group = ProductGroup.new
  end

  # GET /product_groups/1/edit
  def edit
  end

  # POST /product_groups
  # POST /product_groups.json
  def create
    @product_group = ProductGroup.new(product_group_params)

    respond_to do |format|
      if @product_group.save
        format.html { redirect_to @product_group, notice: 'Product group was successfully created.' }
        format.json { render :show, status: :created, location: @product_group }
      else
        format.html { render :new }
        format.json { render json: @product_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_groups/1
  # PATCH/PUT /product_groups/1.json
  def update
    respond_to do |format|
      if @product_group.update(product_group_params)
        format.html { redirect_to @product_group, notice: 'Product group was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_group }
      else
        format.html { render :edit }
        format.json { render json: @product_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_groups/1
  # DELETE /product_groups/1.json
  def destroy
    @product_group.destroy
    respond_to do |format|
      format.html { redirect_to product_groups_url, notice: 'Product group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_group
      @product_group = ProductGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_group_params
      params.require(:product_group).permit(:name, :description)
    end
end

app/views/product_groups/_form.html.erb
<div class="fc-card">
  <%= form_for(product_group)  do |f| %>
    <div class="form-group">
      <% if product_group.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(product_group.errors.count, "error") %> prohibited this product_group from being saved:</h2>

          <ul>
          <% product_group.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control' %>
      </div>

      <div class="actions">
        <%= f.submit %>
      </div>
    </div>
  <% end %>
</div>

app/views/product_groups/edit.html.erb
<h1>Editing Product Group</h1>

<%= render 'form', product_group: @product_group %>

<%= link_to 'Show', @product_group %> |
<%= link_to 'Back', product_groups_path %>

app/views/product_groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Product Groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_groups.each do |product_group| %>
      <tr>
        <td><%= product_group.name %></td>
        <td><%= product_group.description %></td>
        <td><%= link_to 'Show', product_group %></td>
        <td><%= link_to 'Edit', edit_product_group_path(product_group) %></td>
        <td><%= link_to 'Destroy', product_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product Group', new_product_group_path %>

app/views/product_groups/new.html.erb
<h1>New Product Group</h1>

<%= render 'form', product_group: @product_group %>

<%= link_to 'Back', product_groups_path %>

app/views/product_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product_group.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product_group.description %>
</p>

<%= link_to 'Edit', edit_product_group_path(@product_group) %> |
<%= link_to 'Back', product_groups_path %>