config/routes.rb
Rails.application.routes.draw do
  
  ## Frontend Website Routes
  root to: 'frontend#index'
  get 'blog', to: 'frontend#blog', as: :blog
  get 'order', to: 'frontend#order', as: :order
  get 'products', to: 'frontend#products', as: :frontend_products
  get 'about', to: 'frontend#about', as: :about
  get 'contact', to: 'frontend#contact', as: :contact
  get 'cart', to: 'frontend#cart', as: :cart
  get 'checkout/account', to: 'frontend#checkout_account', as: :checkout_account
  get 'checkout/shipping', to: 'frontend#checkout_shipping', as: :checkout_shipping
  get 'checkout/payment', to: 'frontend#checkout_payment', as: :checkout_payment
  get 'checkout/confirmation', to: 'frontend#checkout_confirmation', as: :checkout_confirmation

  resources :order_items, only: [:create, :update, :destroy]
  resources :orders, only: [:update]

  post 'addresses', to: 'addresses#create'
  post 'checkout/payment', to: 'frontend#checkout_payment_fulfillment', as: :checkout_payment_fulfillment

  ## User Account Routes
  get 'account', to: 'account#index', as: :account
  scope 'account' do
    get 'subscriptions', to: 'account#subscriptions', as: :account_subscriptions
    post 'subscriptions/:id/cancel', to: 'subscriptions#cancel', as: :cancel_subscription
    # get 'billing', to: 'account#billing', as: :account_billing
    get 'settings', to: 'account#settings', as: :account_settings
    resources :addresses, except: :destroy
  end


  ## Verify Let's Encrypt
  get '.well-known/acme-challenge/krDZFT9l6mV5mh29OuTAinc3-uCDZudYljSon6gH41I', to: 'frontend#letsencrypt_develop'
  get '.well-known/acme-challenge/bZQzDR1ujn0FQ0UuIJYwrpHINu-Jkpnv4I1XtAvcNhs', to: 'frontend#letsencrypt_staging'
  get '.well-known/acme-challenge/4ahKSK8Se_NIIpBnfipB0xIFNU6mhg69pocJU4GzV8o', to: 'frontend#letsencrypt_production'


  ## 301's from old Website
  get 'blogs/news', to: redirect('http://blog.herbata.co', status: 301)
  get 'blogs/news/:name', to: redirect('http://blog.herbata.co/%{name}', status: 301)
  get 'collections/all', to: redirect('https://herbata.co/products', status: 301)
  get 'products/one-month-subscription', to: redirect('https://herbata.co/products', status: 301)
  get 'products/3-month-subscription', to: redirect('https://herbata.co/products', status: 301)

  

  ## Devise Routes
  devise_for :users, :controllers => {
    registrations: 'registrations',
    sessions: 'sessions',
    passwords: 'passwords'
  }
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    delete 'logout', to: 'devise/sessions#destroy'
  end


  ## Backend Access Routes
  get 'farm', to: 'dashboard#index', as: :dashboard
  scope 'farm' do
    resources :orders, only: [:index, :show, :update] do
      resources :order_statuses, only: [:index, :create]
    end
    get 'orders/:id', to: 'orders#show', as: :order_detail

    resources :product_groups
    resources :products
    resources :coupons
    resources :subscriptions
    resources :customers
  end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :customer
  belongs_to :product
  belongs_to :coupon

  def self.create_subscription(product, customer)
    if product.product_type.id === 2
      stripe_subscription = Stripe::Subscription.create(
        :customer => customer.stripe_id,
        :plan => product.stripe_id
      )

      Subscription.create!({
        uuid: SecureRandom.hex,
        customer: customer,
        product: product,
        stripe_id: stripe_subscription[:id],
        stripe_customer_id: stripe_subscription[:customer],
        stripe_plan_id: stripe_subscription[:plan][:id],
        quantity: stripe_subscription[:quantity],
        tax_percent: stripe_subscription[:tax_percent],
        trial_end: stripe_subscription[:trial_end],
        canceled_at: stripe_subscription[:canceled_at]
      })

    end
  end

  def cancel
    stripe_subscription = Stripe::Subscription.retrieve(self.stripe_id)
    res = stripe_subscription.delete

    self.active = false if res[:canceled] || res[:cancel_at_period_end]
    self.canceled_at = Time.now
    self.save!
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  layout "application"
  before_action :authenticate_user!
  
  before_action :set_subscription, only: [:show, :edit, :update, :destroy, :cancel]

  def index
    @subscriptions = Subscription.all
  end

  def show
  end

  def new
    @subscription = Subscription.new
  end

  def edit
  end

  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    # @subscription.destroy
    # respond_to do |format|
    #   format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  def cancel
    if @subscription.cancel
      redirect_to account_subscriptions_path, notice: "Your subscription has been cancelled. We are sad. Come back!"
    end
  end

  private
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    def subscription_params
      params.require(:subscription).permit(:customer_id, :product_id, :coupon_id, :uuid, :stripe_subscription_id, :stripe_customer_id, :stripe_coupon_id, :stripe_plan_id, :quantity, :tax_percent, :trial_end, :canceled_at)
    end
end

app/views/subscriptions/_form.html.erb
<%= form_for(subscription) do |f| %>
  <% if subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% subscription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customer_id %>
    <%= f.text_field :customer_id %>
  </div>

  <div class="field">
    <%= f.label :product_id %>
    <%= f.text_field :product_id %>
  </div>

  <div class="field">
    <%= f.label :coupon_id %>
    <%= f.text_field :coupon_id %>
  </div>

  <div class="field">
    <%= f.label :uuid %>
    <%= f.text_field :uuid %>
  </div>

  <div class="field">
    <%= f.label :stripe_id %>
    <%= f.text_field :stripe_id %>
  </div>

  <div class="field">
    <%= f.label :stripe_customer_id %>
    <%= f.text_field :stripe_customer_id %>
  </div>

  <div class="field">
    <%= f.label :stripe_coupon_id %>
    <%= f.text_field :stripe_coupon_id %>
  </div>

  <div class="field">
    <%= f.label :stripe_plan_id %>
    <%= f.text_field :stripe_plan_id %>
  </div>

  <div class="field">
    <%= f.label :quantity %>
    <%= f.number_field :quantity %>
  </div>

  <div class="field">
    <%= f.label :tax_percent %>
    <%= f.text_field :tax_percent %>
  </div>

  <div class="field">
    <%= f.label :trial_end %>
    <%= f.text_field :trial_end %>
  </div>

  <div class="field">
    <%= f.label :canceled_at %>
    <%= f.datetime_select :canceled_at %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing Subscription</h1>

<%= render 'form', subscription: @subscription %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<h6>Ecommerce</h6>
<h2>Subscriptions</h2>
<br>

<p id="notice"><%= notice %></p>


<table class="fc-table table">
  <thead>
    <tr>
      <th>Customer</th>
      <th>Product</th>
      <th>Coupon</th>
      <th>Uuid</th>
      <th>Stripe subscription</th>
      <th>Stripe customer</th>
      <th>Stripe coupon</th>
      <th>Stripe plan</th>
      <th>Quantity</th>
      <th>Tax percent</th>
      <th>Trial end</th>
      <th>Canceled at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.customer %></td>
        <td><%= subscription.product %></td>
        <td><%= subscription.coupon %></td>
        <td><%= subscription.uuid %></td>
        <td><%= subscription.stripe_id %></td>
        <td><%= subscription.stripe_customer_id %></td>
        <td><%= subscription.stripe_coupon_id %></td>
        <td><%= subscription.stripe_plan_id %></td>
        <td><%= subscription.quantity %></td>
        <td><%= subscription.tax_percent %></td>
        <td><%= subscription.trial_end %></td>
        <td><%= subscription.canceled_at %></td>
        <td><%= link_to 'Show', subscription %></td>
        <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
        <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<h1>New Subscription</h1>

<%= render 'form', subscription: @subscription %>

<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @subscription.customer %>
</p>

<p>
  <strong>Product:</strong>
  <%= @subscription.product %>
</p>

<p>
  <strong>Coupon:</strong>
  <%= @subscription.coupon %>
</p>

<p>
  <strong>Uuid:</strong>
  <%= @subscription.uuid %>
</p>

<p>
  <strong>Stripe id:</strong>
  <%= @subscription.stripe_id %>
</p>

<p>
  <strong>Stripe customer:</strong>
  <%= @subscription.stripe_customer_id %>
</p>

<p>
  <strong>Stripe coupon:</strong>
  <%= @subscription.stripe_coupon_id %>
</p>

<p>
  <strong>Stripe plan:</strong>
  <%= @subscription.stripe_plan_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @subscription.quantity %>
</p>

<p>
  <strong>Tax percent:</strong>
  <%= @subscription.tax_percent %>
</p>

<p>
  <strong>Trial end:</strong>
  <%= @subscription.trial_end %>
</p>

<p>
  <strong>Canceled at:</strong>
  <%= @subscription.canceled_at %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>